### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/turtle-snowflakes#2]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by bennuttall** [comment]
Cover image added. Does this resource require any in-worksheet diagrams?

**Comment by bennuttall** [comment]
No hardware required so not waiting on components

**Comment by bennuttall** [comment]
Step numbers need removing from [worksheet](worksheet.md)
