### ISSUE TITLE
Title discrepancy

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/turtle-snowflakes#4]
Title on resources index page is "Turtle Snowflakes" (as in the alt text over the project image) but on the resource itself it's "Snowflake Turtle": I don't know how to change the header title/index page title so they don't conflict: I can't find them in the repository, so I assume they are part of a template, or part of the actual website code.

**Comment by bennuttall** [comment]
The resource title is recorded in [meta.yml](https://github.com/raspberrypilearning/turtle-snowflakes/blob/master/meta.yml). Should be Turtle Snowflakes.

**Comment by LornaLynch** [comment]
Thanks, I'll sort it now.
