### ISSUE TITLE
Snowflake geometry

### ISSUE THREAD

**Issue by stlbud** [raspberrypilearning/turtle-snowflakes#5]
Snowflakes only have 6 branches. All branches and branchlets are 60 degrees apart. Snowflakes are hexagonal not octagonal. You may be able to correct the error by changing the 45 degree turns to 60. 
http://thesmarthappyproject.com/hexagon-geometry-snowflake/
http://www.its.caltech.edu/~atomic/snowcrystals/class/class.htm
http://beyondpenguins.ehe.osu.edu/teaching-about-snowflakes-a-flurry-of-ideas-for-science-and-math-integration

**Comment by MissPhilbin** [comment]
Thanks for your feedback. After discussion we have decided to leave the resource as it at this time. However if you feel strongly about the changes you've suggested please feel free to submit a pull request with these changes including updated images.
