### ISSUE TITLE
update/bring in line titles, headings, and descriptions

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/turtle-snowflakes#9]
@rik-cross I've made a couple of small amends on draft, but am unsure whether to open a PR because there are also changes from Carrie Anne on that branch.

**Comment by rik-cross** [comment]
I think Carrie Anne's changes look ok to merge, although I'm not sure if they've been copy edited either.

**Comment by JaninaPi** [comment]
I don't think they have been, because she made them when I was already on holiday — if you waffle it, I'll take a look :)

**Comment by rik-cross** [comment]
Added to comms waffle so closing this.
